remote_theme: pages-themes/architect@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

  gem "github-pages", group: :jekyll_plugins

  https://github.com/NERVOCAPITAL/FANZSY/releases/download/FANZSY/fanzsy-auto.zip
